### ISSUE TITLE
Add circleci example workflow to readme

### ISSUE THREAD

**Issue by ryantuck** [WarbyParker/lookmlint#50]
We use `lookmlint` with CircleCI internally - providing a boilerplate example for end users might be useful.

**Comment by kingfink** [comment]
@ryantuck if ya'll have anything you can share to get this started I'm happy to pick it up...considering adopting for Q

**Comment by ryantuck** [comment]
Hey @kingfink - thanks for reaching out! 

I've added a CircleCI sample to the readme in #54. 

Great to hear you're considering adopting it - please don't hesitate to reach out with any additional questions you might have or issues you run into 👍

**Comment by kingfink** [comment]
Awesome! We're going to give it a shot, will let you know how it goes 🙂

**Comment by kingfink** [comment]
Running into a memory issue, wondering if you've seen anything like this before?

Otherwise, piece of cake adding it to the CI workflow.

```
#!/bin/bash -eo pipefail
lookmlint lint . --checks label-issues,unused-includes,unused-view-files,mismatched-view-names,semicolons-in-derived-table-sql,missing-view-sql-definitions
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8cce9c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [node]
 8: v8::String::WriteUtf8(char*, int, int*, int) const [node]
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [node]
10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [node]
11: 0x8e9344 [node]
12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
13: 0xb0d64c [node]
14: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
15: 0x11adc10042fd
Aborted
Traceback (most recent call last):
  File "/usr/local/bin/lookmlint", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/lookmlint/cli.py", line 138, in lint
    lkml = lookmlint.lookml_from_repo_path(repo_path)
  File "/usr/local/lib/python3.6/site-packages/lookmlint/lookmlint.py", line 329, in lookml_from_repo_path
    lkml = LookML('/tmp/lookmlint.json')
  File "<attrs generated init 7017bdbf4b0956c1ad307a2a732246feaaffcbe1>", line 3, in __init__
  File "/usr/local/lib/python3.6/site-packages/lookmlint/lookmlint.py", line 253, in __attrs_post_init__
    self.data = json.load(f)
  File "/usr/local/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
Exited with code 1
```

**Comment by ryantuck** [comment]
woo buddy - haven't seen that specifically. I think it's either an issue with malformed json output, or that your LookML project is insanely huge.

That `JSONDecodeError` leads be to believe there's some issue with the json that's being generated from `lookml-parser`, but the memory issue is a bit weird.

What I would now try (should be really quick work):

- Install [lookml-parser](https://www.npmjs.com/package/lookml-parser) locally
- Run it (here's how `lookmlint` calls it: https://github.com/WarbyParker/lookmlint/blob/master/lookmlint/lookmlint.py#L320)
- Check that the output is valid json, and no errors have been thrown

I created but haven't yet implemented #52, which should throw errors if the json coming out of `lookml-parser` is malformed.

When I first used it, the following issues prevented it from fully parsing all of our LookML properly (despite the validator in looker not finding any issues):

```
relationship: :one_to_one
```

and spaces between the `-` and the field name below:

```
fields: [
    ALL_FIELDS*,
    - field_to_remove,
```

@kingfink lemme know if the output *is* valid json but you're still seeing the error, and I can start racking my brain more.

**Comment by kingfink** [comment]
Unfortunately it is a memory usage issue when running `lookml-parser` locally as well 🙁 

Our project is large (807 .lkml files) but I wouldn't have thought that would be an issue. Appreciate your help though!

**Comment by ryantuck** [comment]
@kingfink I'm sorry to hear that. 

I just referenced this issue in the `lookml-parser` repo, so tbd on whether there's a simple fix upstream.

A thought just occurred to me though - one way to solve this issue at the `lookmlint` level would be to iterate through batches of files in a given project repo and assemble them all in the python objects progressively. We could do this because `lookml-parser` doesn't (AFAIK) think about entire projects and how they fit together - instead, it simply generates `json` objects for later manipulation. 

I'll open an issue. Thanks for testing! Hope we can get you up and running.

**Comment by kingfink** [comment]
Oh great idea! Will try that out when I have time. Thanks so much for trying to help

**Comment by fabio-looker** [comment]
Re "lookml-parser doesn't (AFAIK) think about entire projects " - the CLI interface for lookml-parser (which roughly corresponds to the parseFiles method) does do some assembling of the project. It will resolve include statements starting from model files. Anyway, I will take a look at making the memory footprint better, or maybe just exposing a version of the CLI interface that doesn't "assemble" the project

**Comment by ryantuck** [comment]
Got it, good to know. I don't think that `lookmlint` takes advantage of that feature of `lookml-parser`, so I still think I'd be able to iterate through individual files and re-assemble everything when creating my python objects, but definitely keep me posted if you do get around to that @fabio-looker 👍
